// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoemTAFgiJy8d22rrDVI2f1djvL6O1cs0',
    appId: '1:1058329396555:web:e9aeef9f5bd3bf686ed4ce',
    messagingSenderId: '1058329396555',
    projectId: 'brownbook-86cd8',
    authDomain: 'brownbook-86cd8.firebaseapp.com',
    storageBucket: 'brownbook-86cd8.firebasestorage.app',
    measurementId: 'G-CM7ZZ1FD0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJux0aA8I6PdoethEcUHPIDsLRHyHWzrk',
    appId: '1:1058329396555:android:def29e59eda9bd686ed4ce',
    messagingSenderId: '1058329396555',
    projectId: 'brownbook-86cd8',
    storageBucket: 'brownbook-86cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2LvN2LfPP9QqEg4BS4MAZVtgfF5uyBp8',
    appId: '1:1058329396555:ios:79d1a8d02e5cabd66ed4ce',
    messagingSenderId: '1058329396555',
    projectId: 'brownbook-86cd8',
    storageBucket: 'brownbook-86cd8.firebasestorage.app',
    iosBundleId: 'com.example.brownbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2LvN2LfPP9QqEg4BS4MAZVtgfF5uyBp8',
    appId: '1:1058329396555:ios:79d1a8d02e5cabd66ed4ce',
    messagingSenderId: '1058329396555',
    projectId: 'brownbook-86cd8',
    storageBucket: 'brownbook-86cd8.firebasestorage.app',
    iosBundleId: 'com.example.brownbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoemTAFgiJy8d22rrDVI2f1djvL6O1cs0',
    appId: '1:1058329396555:web:9827bdbe6dbff2c96ed4ce',
    messagingSenderId: '1058329396555',
    projectId: 'brownbook-86cd8',
    authDomain: 'brownbook-86cd8.firebaseapp.com',
    storageBucket: 'brownbook-86cd8.firebasestorage.app',
    measurementId: 'G-ZXPHTBTZ89',
  );
}
